// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE


var Easing = /* module */[
  /* easeIn */"easeIn",
  /* easeInEaseOut */"easeInEaseOut",
  /* easeOut */"easeOut",
  /* linear */"linear",
  /* keyboard */"keyboard"
];

export {
  Easing ,
  
}
/* No side effect */
