// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";
import * as PromiseUtils$ReactNative from "./PromiseUtils.bs.js";

function getInitialURL(param) {
  return ReactNative.Linking.getInitialURL().then(PromiseUtils$ReactNative.nullableToOption);
}

export {
  getInitialURL ,
  
}
/* react-native Not a pure module */
