// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE


var Orientation = /* module */[
  /* landscape */"landscape",
  /* landscapeLeft */"landscape-left",
  /* landscapeRight */"landscape-right",
  /* portrait */"portrait",
  /* portraitUpsideDown */"portrait-upside-down"
];

export {
  Orientation ,
  
}
/* No side effect */
