// Generated by BUCKLESCRIPT VERSION 6.0.0-dev.1, PLEASE EDIT WITH CARE

import * as ReactNative from "react-native";

function get(name) {
  return ReactNative.NativeModules[name];
}

export {
  get ,
  
}
/* react-native Not a pure module */
